### ISSUE TITLE
receive-offer Event Handler Not Invoked When User Joins Room

### ISSUE THREAD

**Issue by Hasnain-Memon** [Hasnain-Memon/google-meet-clone#1]
When a user joins an existing room in my video calling application, the receive-offer event is emitted from the server (verified in the Network tab), but the handler on the client side is not invoked. This is preventing the video call connection from being established between users.

Expected Behavior :
When a user joins the room and the receive-offer event is emitted from the server, the client-side handler should receive the event and process the WebRTC offer to establish a connection between peers.

Actual Behavior:
The receive-offer event is emitted from the server (verified via the Network tab), but the client-side event handler for the receive-offer is not being triggered. No errors are logged in the console.

Steps to Reproduce: 
1. Start the signaling server. (for the signaling server clone this repo: https://github.com/Hasnain-Memon/Backend-LinkUpLive-)
2. Open two browser instances (or two devices) and join the same room.
3. Observe the Network tab to confirm the receive-offer event is sent.
4. Notice that the client-side event handler for the receive-offer is not invoked.

Additional Context : 
I've confirmed that the event is emitted successfully from the server and is visible in the browser’s Network tab, but the client-side handler doesn't log the event or execute any code.
I'm using TypeScript with Next.js and Zustand for state management.

**Comment by kiritocode1** [comment]
You Know, Defining an Issue properly is a skill in itself

**Comment by Hasnain-Memon** [comment]
> You Know, Defining an Issue properly is a skill in itself

I completely agree, defining an issue properly is definitely a skill. I've updated the issue description with more details to make it clearer and easier to understand.
